# Generated by Django 5.0.6 on 2024-05-28 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('publish', models.BooleanField(default=False, verbose_name='Publication')),
                ('date', models.DateTimeField(auto_now=True)),
                ('conten', models.TextField(verbose_name='Text_articles')),
                ('description', models.TextField(blank=True, default='')),
                ('auteur', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ['title'],
            },
        ),
    ]
